title: flatMap(Oslo) 2018
email: flatmap@arktekk.no
description: > # flatMap(Oslo) 2018 functional programming conference
baseurl: ""
url: "http://2018.flatmap.no"

destination: docs
include: ["_pages"]
permalink: /:title/
exclude: [vendor]

includes:
  - _pages

markdown: kramdown

gems:
- susy

page_gen:
- data: talks
  template: talk
  name: page_name
  dir: talks
