title: flatMap(Oslo) 2018
email: flatmap@arktekk.no
description: > # flatMap(Oslo) 2018 functional programming conference
baseurl: ""
url: "http://2018.flatmap.no"

destination: docs
include: ["_pages"]
permalink: /:title/
exclude: [vendor]
includes:
  - _pages

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

page_gen:
- data: talks
  template: talk
  name: page_name
  dir: talks
